server:
  port: 9080
  shutdown: graceful
  forward-headers-strategy: framework
spring:
  batch:
    job:
      enabled: false
    jdbc:
      isolation-level-for-create: DEFAULT
      initialize-schema: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/{vendor}/common
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        default_schema: black
        format_sql: true
      jdbc:
        time_zone: UTC
#  main:
#    web-application-type: servlet
#    allow-bean-definition-overriding: true
---
# local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: 'jdbc:mysql://localhost:3306/hunters_dev?characterEncoding=UTF-8'
    username: 'root'
    password: '1234'
